"""Fix user-content relationship and add contents back_populates

Revision ID: 874f72ce9b56
Revises: 32ecd42b855a
Create Date: 2025-08-26 18:24:30.247557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874f72ce9b56'
down_revision: Union[str, None] = '32ecd42b855a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
